### PR TITLE
Restructure lab as the second part of a two-part challenge

### LINKED ISSUE #17: Fixture X's and O's still in v-000
I'm not sure (https://github.com/learn-co-curriculum/js-tictactoe-rails-api/commit/2b4584eab17bedb78579b86927ddf34deff3d841) made it into `v-000`.  The error was still in what got cloned for me a couple of days ago.

Thanks, @mendelB for helping me find this!

### LINKED ISSUE #19: Issue with active_model_serializers ver. 0.10.0
Two Jasmine tests (described at the bottom) which deal with the game's persistence seem to be written assuming active_model_serializers ver. 0.9.4, which has a different JSON layout. This makes the Jasmine tests pass for one solution, even though it won't work in the browser, and it makes the other solution work in the browser, but not passing Jasmine tests. 
Here is an example:

**This is how the JSON looks with ver. 0.9.4**

screenshot 2016-06-09 09 57 27

**And this is how the JSON looks with ver. 0.10.0**

screenshot 2016-06-09 09 59 04

The two Jasmine tests (tictactoe.spec.js) are described as:
_"if i click the previous game button and no games have been saved i should get no games in the DOM"_
_"if i click the previous game button and a game has already been saved it should add the previous game to the DOM"_

### LINKED ISSUE #21: create route is incorrect I believe
I believe the POST route in the readme should be POST '/games' rather than POST '/games/:id' to be RESTful

### LINKED ISSUE #22: Jasmine tests should be removed from this lab
Jasmine tests should be removed, OR labs should be re-written w/o jasmine tests (using mocha instead) and update in the Full Stack Web Dev. with React track.

@jmburges @Lukeghenco @cernanb

### PR DESCRIPTION
**Pull request by gj**
Fixes #17 
Fixes #19 
Fixes #21 
Fixes #22

### CODE REVIEW

File: test/tictactoeTest.js [hunk 1]
```diff
@@ -0,0 +1,831 @@
...
+
+    it("loads the saved game's state into the board", () => {
+      previousButton.click();
+
+      requests[0].respond(
+        200,
+        { 'Content-Type': 'application/json' },
+        JSON.stringify(
+          {
+            "data": [
```
Comment (jmburges) [inline test/tictactoeTest.js]: There must be a way to write a quick function to abstract this out. You've repeated it at least three times

Comment (jmburges) [inline test/tictactoeTest.js]: My rule is write once ok, write twice, ok, third time....encapsulate!

File: test/tictactoeTest.js [hunk 2]
```diff
@@ -0,0 +1,831 @@
+try {
```
Comment (gj) [inline test/tictactoeTest.js]: Done.
